version: "2"
services:

  # Jaeger
  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "16686:16686"
      - "14268"
      - "14250"

  # Collector
  tailsamplingbackend1:
    image: otel/opentelemetry-collector-contrib-dev
    command: ["--config=/etc/otel-collector-config.yaml", "${OTELCOL_ARGS}"]
    volumes:
      - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml
    ports:
      - "1888"   # pprof extension
      - "8888"   # Prometheus metrics exposed by the collector
      - "8889"   # Prometheus exporter metrics
      - "13133" # health_check extension
      - "4317"        # OTLP gRPC receiver
      - "55670" # zpages extension
    depends_on:
      - jaeger

  # Collector
  tailsamplingbackend2:
    image: otel/opentelemetry-collector-contrib-dev
    command: ["--config=/etc/otel-collector-config.yaml", "${OTELCOL_ARGS}"]
    volumes:
      - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml
    ports:
      - "1888"   # pprof extension
      - "8888"   # Prometheus metrics exposed by the collector
      - "8889"   # Prometheus exporter metrics
      - "13133" # health_check extension
      - "4317"        # OTLP gRPC receiver
      - "55670" # zpages extension
    depends_on:
      - jaeger

  # Collector
  tailsamplingbackend3:
    image: otel/opentelemetry-collector-contrib-dev
    command: ["--config=/etc/otel-collector-config.yaml", "${OTELCOL_ARGS}"]
    volumes:
      - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml
    ports:
      - "1888"   # pprof extension
      - "8888"   # Prometheus metrics exposed by the collector
      - "8889"   # Prometheus exporter metrics
      - "13133" # health_check extension
      - "4317"        # OTLP gRPC receiver
      - "55670" # zpages extension
    depends_on:
      - jaeger

  # Agent
  otel-agent:
    image: otel/opentelemetry-collector-contrib-dev
    command: ["--config=/etc/otel-agent-config.yaml", "${OTELCOL_ARGS}"]
    volumes:
      - ./otel-agent-config.yaml:/etc/otel-agent-config.yaml
    ports:
      - "14250"       # Jaeger grpc receiver
      - "14268"       # Jaeger http thrift receiver
      - "55678"       # OpenCensus receiver
      - "4317"        # OTLP gRPC receiver
      - "9411"        # Zipkin receiver
      - "1777"   # pprof extension
      - "55679" # zpages extension
      - "13133"       # health_check
    depends_on:
      - tailsamplingbackend1
      - tailsamplingbackend2
      - tailsamplingbackend3

  # Synthetic load generators
  jaeger-emitter:
    image: omnition/synthetic-load-generator:1.0.29
    environment:
      - JAEGER_COLLECTOR_URL=http://otel-agent:14268
      # - TOPOLOGY_FILE=./topologies/100_000_spans_per_second.json
    depends_on:
      - otel-agent
