receivers:
  otlp:
    protocols:
      grpc:

exporters:
  logging:

  jaeger:
    endpoint: jaeger:14250
    insecure: true

processors:
  tail_sampling:
    decision_wait: 10s
    policies:
      [
        {
          name: sample-http-errors, 
          type: numeric_attribute,
          numeric_attribute:
          {
            key: http.status_code,
            min_value: 400,
            max_value: 599
          }
        }
      ]

extensions:
  health_check:
  pprof:
    endpoint: :1888
  zpages:
    endpoint: :55679

service:
  extensions: [pprof, zpages, health_check]
  pipelines:
    traces:
      receivers: [otlp]
      processors: [tail_sampling]
      exporters: [logging, jaeger]
