---
apiVersion: v1
kind: ConfigMap
metadata:
  name: otel-collector-config
data:
  config.yaml: |-
    receivers:
      otlp:
        protocols:
          grpc:
      opencensus:
      jaeger:
        protocols:
          grpc:
          thrift_http:
      zipkin:
    exporters:
      otlp:
        endpoint: "otel-collector:4317"
        insecure: true
    processors:
      tail_sampling:
        decision_wait: 10s
        policies:
          [
            {
              name: sample-http-errors, 
              type: numeric_attribute,
              numeric_attribute:
              {
                key: http.status_code,
                min_value: 400,
                max_value: 600
              }
            }
          ]
    service:
      pipelines:
        traces:
          receivers: [otlp]
          processors: [tail_sampling]
          exporters: [otlp]

---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: otel-collector
  labels:
    app: opentelemetry
    component: otel-collector
spec:
  selector:
    matchLabels:
      app: opentelemetry
      component: otel-collector
  template:
    metadata:
      labels:
        app: opentelemetry
        component: otel-collector
    spec:
      containers:
      - name: otel-collector
        image: otel/opentelemetry-collector-contrib:0.22.0
        resources:
          limits:
            cpu: 100m
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 200Mi
        volumeMounts:
        - mountPath: /etc/otel/config.yaml
          name: data
          subPath: config.yaml
          readOnly: true
      terminationGracePeriodSeconds: 30
      volumes:
      - name: data
        configMap:
          name: otel-collector-config

---
apiVersion: v1
kind: Service
metadata:
  name: otel-collector
  labels:
    app: opentelemetry
    component: otel-collector
spec:
  ports:
  - name: metrics # Default endpoint for querying metrics.
    port: 8888
  - name: trace-grpc
    port: 4317
  selector:
    component: otel-collector


---
apiVersion: v1
kind: ConfigMap
metadata:
  name: otel-agent-config
data:
  config.yaml: |-
    receivers:
      otlp:
        protocols:
          grpc:
      jaeger:
        protocols:
          grpc:
          thrift_http:
    exporters:
      loadbalancing:
        protocol:
          otlp:
            # all options from the OTLP exporter are supported
            # except the endpoint
            timeout: 1s
            insecure: true
        resolver:
          static:
            hostnames:
            - tailsamplingbackend1:4317
            - tailsamplingbackend2:4317
            - tailsamplingbackend3:4317
    processors:
      batch:
    extensions:
      pprof:
        endpoint: :1777
      zpages:
        endpoint: :55679
      health_check:
    service:
      extensions: [health_check, pprof, zpages]
      pipelines:
        traces:
          receivers: [otlp, jaeger]
          processors: [batch]
          exporters: [loadbalancing]

